"""Kernel-dataplane markers (`marker add_kernel`) — AF_PACKET-sniffed signals.

Docker nodes bridge veth → kernel bridge → veth inside the kernel, so a relay-
hooked `mark` filter never sees that traffic. `marker add_kernel` sniffs an
interface directly (AF_PACKET/SOCK_RAW, non-promisc, per-marker reader thread)
and emits the same MARK signals — plus an optional pcap — on BPF match. This
test drives a veth pair and asserts: signals with the right dir/len/tag/link,
both directions, the dir filter, pcap append, enable off/on, delete
idempotency, the error paths, and coexistence with `capture start_kernel`.

Traffic is generated by injecting raw Ethernet/IPv4/ICMP frames through
AF_PACKET sockets rather than ping: an injection bound to VETH_A shows up on
the marker's socket as PACKET_OUTGOING (host end sending = node receiving →
dir=rx), one bound to VETH_B crosses the veth and arrives as PACKET_HOST
(node sent → dir=tx). This is deterministic in any environment — ping depends
on in-namespace ARP/IPv6 autoconf, which is not reliable under `unshare -Urn`.

Requires CAP_NET_RAW (injection + sniffing) — run under sudo (or
`unshare -Urn`). Self-skips otherwise so the userspace CI job stays green.
Uses the in-repo ./ubridge (the installed binary may lack the marker module).
"""
import os
import sys
import re
import socket
import struct
import subprocess
import time

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "brctl"))
from common import Ubridge, Results  # noqa: E402

PREFIX = "ubmk-"
PORT = 13090
VETH_A = PREFIX + "a"
VETH_B = PREFIX + "b"
PCAP = "/tmp/ubmk-marker.pcap"
PCAP2 = "/tmp/ubmk-capture.pcap"
REPO_UBRIDGE = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "ubridge"))


def _ip(args):
    return subprocess.run(["ip"] + args, capture_output=True, text=True)


def _exists(name):
    return _ip(["-o", "link", "show", name]).returncode == 0


def _mac(name):
    """Interface MAC via `ip -o link` (sysfs shows the wrong netns under unshare)."""
    out = _ip(["-o", "link", "show", name]).stdout
    m = re.search(r"link/ether ([0-9a-f:]{17})", out)
    return bytes(int(b, 16) for b in m.group(1).split(":"))


def _free_udp():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.bind(("127.0.0.1", 0))
    p = s.getsockname()[1]
    s.close()
    return p


PAYLOAD = b"ubridge-kernel-marker"


def _icmp_frame(dst_mac, src_mac):
    """Ethernet + IPv4 + ICMP echo request; matches libpcap's `icmp` BPF."""
    icmp = struct.pack("!BBHHH", 8, 0, 0, 1, 1) + PAYLOAD
    ip = struct.pack("!BBHHHBBH4s4s", 0x45, 0, 20 + len(icmp), 0x1234, 0, 64, 1, 0,
                     bytes([10, 97, 0, 1]), bytes([10, 97, 0, 2]))
    return dst_mac + src_mac + struct.pack("!H", 0x0800) + ip + icmp


def _inject(iface, frame):
    """Send one raw frame out of `iface` (AF_PACKET, fire-and-forget)."""
    s = socket.socket(socket.AF_PACKET, socket.SOCK_RAW)
    try:
        s.bind((iface, 0))
        s.send(frame)
    finally:
        s.close()


def _stim(m_a, m_b):
    """One frame per direction: out of A (→ OUTGOING → dir=rx) and out of
    B toward A's MAC (crosses the veth → PACKET_HOST → dir=tx)."""
    frame = _icmp_frame(m_a, m_b)   # dst = A's MAC, src = B's MAC
    _inject(VETH_A, frame)
    _inject(VETH_B, frame)


def _drain(sock, timeout):
    """Collect sink datagrams until `timeout` passes with no traffic."""
    out = []
    end = time.time() + timeout
    while True:
        remaining = end - time.time()
        if remaining <= 0:
            break
        sock.settimeout(remaining)
        try:
            data, _ = sock.recvfrom(4096)
        except socket.timeout:
            break
        out.append(data.decode(errors="replace").strip())
    return out


def _kv(line):
    return dict(tok.split("=", 1) for tok in line.split() if "=" in tok)


def main():
    r = Results()

    if os.geteuid() != 0:
        print("  [SKIP] needs CAP_NET_RAW (run under sudo or unshare -Urn)")
        return 0

    # the marker sink is 127.0.0.1 UDP: inside a fresh netns (unshare -Urn)
    # loopback starts DOWN and the signals silently vanish — bring it up
    # (no-op on a real system, where lo is already up)
    subprocess.run(["ip", "link", "set", "lo", "up"], capture_output=True)

    marker_port = _free_udp()
    ms = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    ms.bind(("127.0.0.1", marker_port))

    for p in (PCAP, PCAP2):
        if os.path.exists(p):
            os.remove(p)

    try:
        with Ubridge(port=PORT, binary=REPO_UBRIDGE) as ub:
            c = ub.connect()
            try:
                # veth pair: A carries the marker, B is the far end / injector
                r.check("link veth pair", c.code("link veth %s %s" % (VETH_A, VETH_B)) == "100")
                c.code("link set %s up" % VETH_A)
                c.code("link set %s up" % VETH_B)
                m_a, m_b = _mac(VETH_A), _mac(VETH_B)

                r.check("marker sink", c.code("marker sink 127.0.0.1 %d" % marker_port) == "100")
                c.code("marker node kmnode")

                # --- add + uniqueness (key = ifname + name) + status
                res = c.send('marker add_kernel icmp-m %s "icmp" tag 5 link 7' % VETH_A)
                r.check("add_kernel", res.startswith("100-"), res)
                r.check("duplicate add -> 206",
                        c.code('marker add_kernel icmp-m %s "ip"' % VETH_A) == "206")
                r.check("same name on other iface ok",
                        c.code('marker add_kernel icmp-m %s "icmp"' % VETH_B) == "100")
                r.check("delete on other iface",
                        c.code("marker delete_kernel %s icmp-m" % VETH_B) == "100")
                st = c.send("marker status")
                r.check("status kernel=1", "kernel=1" in st, st.replace("\n", " | "))

                # --- signals: one per direction, with node/filter/tag/link/dir/len
                _stim(m_a, m_b)
                sigs = [_kv(s) for s in _drain(ms, 1.2) if s.startswith("MARK ")]
                frame_len = len(_icmp_frame(m_a, m_b))
                r.check("signals received", len(sigs) == 2, "n=%d" % len(sigs))
                if sigs:
                    r.check("signal fields", all(
                        s.get("node") == "kmnode" and s.get("filter") == "icmp-m"
                        and s.get("tag") == "5" and s.get("link") == "7"
                        and s.get("len") == str(frame_len)
                        for s in sigs), str(sigs[0]))
                    r.check("dir mapping (outgoing=rx, host=tx)",
                            sorted(s["dir"] for s in sigs) == ["rx", "tx"],
                            str(sorted(s["dir"] for s in sigs)))

                # --- enable off: installed but silent; on: instant resume
                c.code("marker enable_kernel %s icmp-m off" % VETH_A)
                _stim(m_a, m_b)
                r.check("enable off -> silent", not _drain(ms, 1.0))
                c.code("marker enable_kernel %s icmp-m on" % VETH_A)
                _stim(m_a, m_b)
                r.check("enable on -> signals resume",
                        len([s for s in _drain(ms, 1.2) if s.startswith("MARK ")]) == 2)
                r.check("enable bad state -> 204",
                        c.code("marker enable_kernel %s icmp-m maybe" % VETH_A) == "204")
                r.check("enable unknown marker -> 208",
                        c.code("marker enable_kernel %s nope on" % VETH_A) == "208")

                # --- pcap append (flushed on delete, like the mark filter)
                c.code("marker delete_kernel %s icmp-m" % VETH_A)
                r.check("add with pcap",
                        c.code('marker add_kernel pc %s "icmp" pcap %s' % (VETH_A, PCAP)) == "100")
                _stim(m_a, m_b)
                # let the reader emit (and pcap-append) both matches before
                # the delete stops it — frames still queued in the socket
                # would be discarded and the record count would flake
                r.check("pcap marker signalled both frames",
                        len([s for s in _drain(ms, 1.2) if s.startswith("MARK ")]) == 2)
                c.code("marker delete_kernel %s pc" % VETH_A)
                r.check("pcap written (2 records)",
                        os.path.exists(PCAP) and os.path.getsize(PCAP) >= 24 + 2 * (16 + frame_len),
                        "size=%s" % os.path.getsize(PCAP) if os.path.exists(PCAP) else "missing")
                _drain(ms, 0.6)   # discard the pcap marker's own signals (emit + pcap on match)

                # --- dir filter: rx keeps only PACKET_OUTGOING (A-side sends)
                r.check("add dir rx",
                        c.code('marker add_kernel rxonly %s "icmp" dir rx' % VETH_A) == "100")
                _stim(m_a, m_b)
                dirsigs = [_kv(s) for s in _drain(ms, 1.2) if s.startswith("MARK ")]
                r.check("dir rx -> only rx signals",
                        len(dirsigs) == 1 and dirsigs[0]["dir"] == "rx",
                        str([s.get("dir") for s in dirsigs]))
                c.code("marker delete_kernel %s rxonly" % VETH_A)

                # --- coexistence with capture start_kernel (separate sockets)
                r.check("capture start_kernel alongside",
                        c.code("capture start_kernel %s %s" % (VETH_B, PCAP2)) == "100")
                r.check("marker while capturing",
                        c.code('marker add_kernel co %s "icmp"' % VETH_A) == "100")
                _stim(m_a, m_b)
                r.check("signals still flow",
                        len([s for s in _drain(ms, 1.2) if s.startswith("MARK ")]) == 2)
                r.check("capture stop", c.code("capture stop_kernel") == "100")
                r.check("capture pcap written",
                        os.path.exists(PCAP2) and os.path.getsize(PCAP2) > 24 + 16)
                c.code("marker delete_kernel %s co" % VETH_A)

                # --- error paths
                r.check("too few params -> 203", c.code("marker add_kernel solo") == "203")
                r.check("all 5 keywords, any order",
                        c.code('marker add_kernel full %s "icmp" pcap %s dir rx linktype EN10MB link 9 tag 3'
                               % (VETH_A, PCAP)) == "100")
                c.code("marker delete_kernel %s full" % VETH_A)
                r.check("missing iface -> 208",
                        c.code('marker add_kernel x %s-nope "ip"' % VETH_A) == "208")
                res = c.send('marker add_kernel bad %s "((("' % VETH_A)
                r.check("bad bpf -> 206 + compile-filter text",
                        res.startswith("206-") and "compile filter" in res, res)
                r.check("bad bpf doesn't break the module",
                        c.code('marker add_kernel ok2 %s "ip"' % VETH_A) == "100")
                c.code("marker delete_kernel %s ok2" % VETH_A)
                r.check("dangling value -> 204",
                        c.code('marker add_kernel x %s "ip" tag' % VETH_A) == "204")
                r.check("unknown keyword -> 204",
                        c.code('marker add_kernel x %s "ip" bogus 1' % VETH_A) == "204")
                r.check("duplicate keyword -> 204",
                        c.code('marker add_kernel x %s "ip" tag 1 tag 2' % VETH_A) == "204")
                r.check("unopenable pcap -> 211",
                        c.code('marker add_kernel x %s "ip" pcap /nonexistent-ubmk-dir/m.pcap' % VETH_A) == "211")
                r.check("delete unknown -> 100 (idempotent)",
                        c.code("marker delete_kernel %s nope" % VETH_A) == "100")

                # --- the interface is replaced under a live marker: enable
                # must fail loudly while it is gone, and re-arm once the
                # device is back (new netdev, new MACs)
                r.check("renew: add", c.code('marker add_kernel renew %s "icmp"' % VETH_A) == "100")
                c.code("marker enable_kernel %s renew off" % VETH_A)
                _ip(["link", "del", VETH_A])
                time.sleep(0.3)                    # the reader hits the dead socket
                res = c.send("marker enable_kernel %s renew on" % VETH_A)
                r.check("renew: enable with the iface gone -> 208 (no lie)",
                        res.startswith("208-"), res)
                r.check("renew: recreate the pair",
                        c.code("link veth %s %s" % (VETH_A, VETH_B)) == "100")
                c.code("link set %s up" % VETH_A)
                c.code("link set %s up" % VETH_B)
                m_a, m_b = _mac(VETH_A), _mac(VETH_B)
                r.check("renew: enable again -> 100 (rebind + re-arm)",
                        c.code("marker enable_kernel %s renew on" % VETH_A) == "100")
                _stim(m_a, m_b)
                r.check("renew: signals flow on the new device",
                        len([s for s in _drain(ms, 1.2) if s.startswith("MARK ")]) == 2)
                c.code("marker delete_kernel %s renew" % VETH_A)
            finally:
                c.close()
    finally:
        if _exists(VETH_A):
            _ip(["link", "del", VETH_A])
        for p in (PCAP, PCAP2):
            if os.path.exists(p):
                os.remove(p)
        ms.close()

    return 0 if r.summary() else 1


if __name__ == "__main__":
    sys.exit(main())
