/*
 *   This file is part of ubridge, a program to bridge network interfaces
 *   to UDP tunnels.
 *
 *   Copyright (C) 2015 GNS3 Technologies Inc.
 *
 *   ubridge is free software: you can redistribute it and/or modify it
 *   under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   ubridge is distributed in the hope that it will be useful, but
 *   WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * The eBPF stateful impairment classifier (kernel-impairment spec B.1).
 *
 * Freestanding: no CO-RE, no BTF-typed pointers, plain packet access.
 * The compiled object is committed (src/tc_impair.bpf.o) and its .text is
 * embedded into the build as an instruction array (src/tc_ebpf_insns.c,
 * regenerated by tools/gen_tc_impair.py) — no runtime clang/libbpf.
 *
 * Verifier-friendly by construction: no loops, every packet access is
 * preceded by a bounds check, L4 ports are only read for TCP/UDP over IPv4
 * with the full L4 header verified present.
 */

#include "tc_impair.h"

/*
 * Minimal freestanding definitions (the BPF target has no libc; pulling in
 * the uapi <linux/bpf.h> drags arch-dependent headers). The __sk_buff
 * offsets used here (len @0, data @80, data_end @84) are the stable uapi
 * layout, asserted from the native side in hypervisor_tc.c.
 */
typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef unsigned long long u64;

#define SEC(NAME) __attribute__((section(NAME), used))

struct min_skb {
    u32 len;                 /* offset 0 */
    u8 _pad[76 - 4];         /* keep data/data_end at their uapi offsets */
    u32 data;                /* offset 76 */
    u32 data_end;            /* offset 80 */
};

/* legacy (pre-BTF) map definition — the loader creates the maps itself and
 * patches the two pseudo-fd loads in the embedded instructions */
struct bpf_map_def {
    u32 type;
    u32 key_size;
    u32 value_size;
    u32 max_entries;
    u32 map_flags;
};

struct bpf_map_def SEC("maps") cfg_map = {
    .type = 2,                              /* BPF_MAP_TYPE_ARRAY */
    .key_size = sizeof(u32),
    .value_size = sizeof(struct tc_impair_cfg),
    .max_entries = 1,
};

struct bpf_map_def SEC("maps") cnt_map = {
    .type = 2,                              /* BPF_MAP_TYPE_ARRAY */
    .key_size = sizeof(u32),
    .value_size = sizeof(struct tc_impair_cnt),
    .max_entries = 1,
};

/* helper functions by stable uapi id */
static void *(*map_lookup_elem)(const void *map, const void *key) = (void *)1;
static u64 (*ktime_get_ns)(void) = (void *)5;

#define TC_ACT_OK    0
#define TC_ACT_SHOT  2

#define ETH_HLEN   14
#define ETH_P_IPV4 0x0800

/*
 * Percentage draw shared by quota and window: compare a 32-bit PRNG value
 * against the netem-style encoding of percent (p * 2^32 / 100, 100 => ~0).
 * Returns 1 (drop) with probability pct/100.
 */
static int pct_drop(volatile u64 *prng, u32 pct)
{
    u64 x = *prng;
    u32 rnd;

    if (pct == 0)
        return 0;
    /* xorshift64* — state must never be zero (userspace seeds with |1) */
    x ^= x >> 12;
    x ^= x << 25;
    x ^= x >> 27;
    *prng = x;
    rnd = (u32)((x * 2685821657736338717ULL) >> 32);
    return rnd < (pct == 100 ? 0xFFFFFFFFu
                             : (u32)(((unsigned long long)pct << 32) / 100));
}

/*
 * Jenkins one-at-a-time fold over the flow-mask-selected header fields.
 * Non-IP frames contribute only their MAC fields; ports only for TCP/UDP
 * over IPv4 with the header verified present. All loads are bytewise (no
 * packet-alignment assumptions).
 */
static u32 flow_hash(struct min_skb *ctx, u32 mask)
{
    u8 *d = (u8 *)(unsigned long)ctx->data;
    u8 *d_end = (u8 *)(unsigned long)ctx->data_end;
    u32 h = 0;
    int i;

    /* Ethernet header must be fully present */
    if (d + ETH_HLEN > d_end)
        return 0;

#define FOLD(b) do { h += (b); h += h << 10; h ^= h >> 6; } while (0)

    if (mask & 0x2)                    /* dst MAC first: frames to the same peer fold alike */
        for (i = 0; i < 6; i++)
            FOLD(d[i]);
    if (mask & 0x1)                    /* src MAC */
        for (i = 6; i < 12; i++)
            FOLD(d[i]);

    if ((u16)((d[12] << 8) | d[13]) == ETH_P_IPV4) {
        u8 *ip = d + ETH_HLEN;
        u8 proto = 0;
        u32 ihl;

        if (ip + 20 > d_end)
            goto out;                  /* truncated IPv4 header: fold MACs only */
        ihl = (ip[0] & 0xf) * 4;
        if (ihl < 20 || ip + ihl + 8 > d_end)
            goto out;                  /* no room for ports: fold MACs (+proto below) only */
        proto = ip[9];
        if (mask & 0x10)
            FOLD(proto);
        if (proto == 6 || proto == 17) {   /* TCP / UDP */
            u8 *l4 = ip + ihl;
            if (mask & 0x4) {
                FOLD(l4[0]);
                FOLD(l4[1]);
            }
            if (mask & 0x8) {
                FOLD(l4[2]);
                FOLD(l4[3]);
            }
        }
    }
out:
    h += h << 3;
    h ^= h >> 11;
    h += h << 15;
    return h;
}

SEC("tc_impair")
int tc_impair_prog(struct min_skb *ctx)
{
    struct tc_impair_cfg *cfg;
    struct tc_impair_cnt *cnt;
    u32 key = 0;
    u64 now;

    cfg = map_lookup_elem(&cfg_map, &key);
    if (!cfg)
        return TC_ACT_OK;
    cnt = map_lookup_elem(&cnt_map, &key);
    if (!cnt)
        return TC_ACT_OK;

    /* 1. nth: drop every Nth packet — exact across CPUs via atomic add.
     * The modulo is done on the low 32 bits: BPF has no native 64-bit
     * modulo (a u64 % would emit a __umoddi3 call the verifier rejects). */
    if (cfg->nth) {
        u32 n = (u32)__sync_fetch_and_add(&cnt->nth_state, 1) + 1;
        if (n % cfg->nth == 0)
            return TC_ACT_SHOT;
    }

    /* 2. quota: after quota_bytes of traffic (counted from the last
     * quota_drop enable), drop each packet with quota_pct probability.
     * Only traffic that survived nth is counted (evaluation is ordered). */
    if (cfg->quota_bytes) {
        __sync_fetch_and_add(&cnt->packets, 1);
        if (__sync_fetch_and_add(&cnt->bytes, ctx->len) + ctx->len
                >= cfg->quota_bytes
            && pct_drop(&cnt->prng_state, cfg->quota_pct))
            return TC_ACT_SHOT;
    }

    /* 3. window: recurring [start, start+len) on the monotonic clock; the
     * program advances start by one len when it expires (single advance,
     * no loop — the CFG update is the only other writer, per spec). */
    if (cfg->win_len_ns) {
        now = ktime_get_ns();
        if (now >= cfg->win_start_ns + cfg->win_len_ns)
            cfg->win_start_ns += cfg->win_len_ns;
        if (now >= cfg->win_start_ns && pct_drop(&cnt->prng_state, cfg->win_pct))
            return TC_ACT_SHOT;
    }

    /* 4. flow: hash the selected fields; remainder 0 modulo target drops */
    if (cfg->flow_mask && cfg->flow_target
        && flow_hash(ctx, cfg->flow_mask) % cfg->flow_target == 0)
        return TC_ACT_SHOT;

    return TC_ACT_OK;
}

char _license[] SEC("license") = "GPL";
